apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kubecost-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Helm Charts configuration
helmCharts:
  - name: cost-analyzer
    repo: https://kubecost.github.io/cost-analyzer/
    version: "2.0.4"
    releaseName: kubecost
    namespace: kubecost
    valuesFile: values.yaml
    includeCRDs: true

# Resources to include
resources:
  - namespace.yaml
  - rbac.yaml
  - network-policy.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: kubecost
  app.kubernetes.io/instance: kubecost
  app.kubernetes.io/component: cost-analyzer
  app.kubernetes.io/part-of: platform-tools
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/version: "2.0.4"

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"

# Target namespace
namespace: kubecost

# Security patches for all deployments
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
          seccompProfile:
            type: RuntimeDefault
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE

# Image transformations
images:
  - name: gcr.io/kubecost1/cost-model
    newTag: prod-1.106.0
  - name: gcr.io/kubecost1/frontend
    newTag: prod-1.106.0

# Configurations
configurations:
  - https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/examples/transformerconfigs/default/namereference.yaml