apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
bases:
  - ../../base

# Namespace override for production
namespace: kubecost

# Production-specific labels
commonLabels:
  environment: production
  tier: platform

# Production-specific annotations
commonAnnotations:
  argocd.argoproj.io/sync-options: "Prune=true"
  
# Name suffix for production
nameSuffix: ""

# Resources specific to production
resources:
  - production-values.yaml
  - monitoring.yaml

# Patches for production environment
patches:
  # Increase resource limits for production
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cost-analyzer
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"

  # Production ingress hostname
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: kubecost-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "kubecost.yourdomain.com"
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "kubecost.yourdomain.com"

  # Enable high availability
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cost-analyzer
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

# Image transformations for production
images:
  - name: gcr.io/kubecost1/cost-model
    newTag: prod-1.106.0
  - name: gcr.io/kubecost1/frontend
    newTag: prod-1.106.0

# Replica transformations
replicas:
  - name: kubecost-cost-analyzer
    count: 2