# Production Environment Kubecost Configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
spec:
  source:
    helm:
      parameters:
        # Production-specific settings with higher resources
        - name: costAnalyzer.resources.requests.cpu
          value: "200m"
        - name: costAnalyzer.resources.requests.memory
          value: "256Mi"
        - name: costAnalyzer.resources.limits.cpu
          value: "1000m"
        - name: costAnalyzer.resources.limits.memory
          value: "1Gi"
        - name: persistentVolume.size
          value: "20Gi"
        - name: ingress.hosts[0].host
          value: "kubecost.your-domain.com"
        - name: ingress.tls[0].hosts[0]
          value: "kubecost.your-domain.com"
        - name: ingress.tls[0].secretName
          value: "kubecost-prod-tls"
        # Error level logging for production
        - name: costAnalyzer.logLevel
          value: "error"
        # Enable enterprise features if token is available
        - name: kubecostToken
          value: "${KUBECOST_TOKEN}"  # Set via environment variable or secret
        # Enable high availability for production
        - name: costAnalyzer.replicas
          value: "2"