apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kubecost-staging

namespace: kubecost

resources:
  - ../../base

patchesStrategicMerge:
  - values-staging.yaml

# Environment-specific labels
commonLabels:
  environment: staging
  
# Environment-specific annotations  
commonAnnotations:
  deployment.environment: "staging"