# Staging-specific Kubecost configuration
# Reduced resources and features for staging environment

# Staging resource allocation - Minimal resources for cost savings
kubecostModel:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Disable ETL for staging to reduce resource usage
kubecostModel:
  etl: false
  warmCache: false
  warmSavingsCache: false

# Staging frontend resources - Minimal allocation
kubecostFrontend:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

# Staging persistence - Smaller storage for staging
persistentVolume:
  enabled: true
  size: "10Gi"
  storageClass: "standard"  # Use standard storage class
  accessModes:
    - ReadWriteOnce

# Staging PostgreSQL configuration - Reduced resources
postgresql:
  enabled: true
  auth:
    postgresPassword: "staging-kubecost-password"
    database: "kubecost_staging"
    username: "postgres"
  primary:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "standard"

# Staging Grafana configuration - Minimal resources
grafana:
  enabled: true
  persistence:
    enabled: true
    size: 3Gi
    storageClass: "standard"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  adminPassword: "staging-grafana-password"

# Staging ingress - No SSL requirement, relaxed security
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # No SSL for staging
    # Relaxed rate limiting for testing
    nginx.ingress.kubernetes.io/rate-limit-connections: "50"
    nginx.ingress.kubernetes.io/rate-limit-rps: "30"
    # Optional: Use staging cert-manager issuer
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: kubecost-staging.yourdomain.com  # CHANGE TO YOUR STAGING DOMAIN
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kubecost-staging-tls
      hosts:
        - kubecost-staging.yourdomain.com  # CHANGE TO YOUR STAGING DOMAIN

# Disable network costs for staging
networkCosts:
  enabled: false

# Staging monitoring - Basic monitoring only
serviceMonitor:
  enabled: true
  additionalLabels:
    prometheus: kube-prometheus
    environment: staging
    tier: platform

# Disable budget alerts for staging
budgetAlertsEnabled: false

# Basic security contexts for staging
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

# No specific affinity for staging - can run anywhere
affinity: {}

# No tolerations for staging
tolerations: []

# No priority class for staging
priorityClassName: ""

# Basic cost allocation for staging
costAnalyzerConfig:
  currencyCode: "USD"
  customPricing:
    enabled: false
  # No cloud provider integration for staging

# Minimal aggregator for staging
kubecostAggregator:
  enabled: false  # Disable for staging to save resources